mkdir -p /Users/timm/tmp/branch
rm /Users/timm/tmp/branch/*
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/Apache_AllMeasurements.csv -e branch  | tee /Users/timm/tmp/branch/Apache_AllMeasurements.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/HSMGP_num.csv -e branch  | tee /Users/timm/tmp/branch/HSMGP_num.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SQL_AllMeasurements.csv -e branch  | tee /Users/timm/tmp/branch/SQL_AllMeasurements.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-A.csv -e branch  | tee /Users/timm/tmp/branch/SS-A.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-B.csv -e branch  | tee /Users/timm/tmp/branch/SS-B.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-C.csv -e branch  | tee /Users/timm/tmp/branch/SS-C.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-D.csv -e branch  | tee /Users/timm/tmp/branch/SS-D.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-E.csv -e branch  | tee /Users/timm/tmp/branch/SS-E.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-F.csv -e branch  | tee /Users/timm/tmp/branch/SS-F.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-G.csv -e branch  | tee /Users/timm/tmp/branch/SS-G.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-H.csv -e branch  | tee /Users/timm/tmp/branch/SS-H.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-I.csv -e branch  | tee /Users/timm/tmp/branch/SS-I.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-J.csv -e branch  | tee /Users/timm/tmp/branch/SS-J.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-K.csv -e branch  | tee /Users/timm/tmp/branch/SS-K.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-L.csv -e branch  | tee /Users/timm/tmp/branch/SS-L.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-M.csv -e branch  | tee /Users/timm/tmp/branch/SS-M.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-N.csv -e branch  | tee /Users/timm/tmp/branch/SS-N.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-O.csv -e branch  | tee /Users/timm/tmp/branch/SS-O.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-P.csv -e branch  | tee /Users/timm/tmp/branch/SS-P.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-Q.csv -e branch  | tee /Users/timm/tmp/branch/SS-Q.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-R.csv -e branch  | tee /Users/timm/tmp/branch/SS-R.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-S.csv -e branch  | tee /Users/timm/tmp/branch/SS-S.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-T.csv -e branch  | tee /Users/timm/tmp/branch/SS-T.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-U.csv -e branch  | tee /Users/timm/tmp/branch/SS-U.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-V.csv -e branch  | tee /Users/timm/tmp/branch/SS-V.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-W.csv -e branch  | tee /Users/timm/tmp/branch/SS-W.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/SS-X.csv -e branch  | tee /Users/timm/tmp/branch/SS-X.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/X264_AllMeasurements.csv -e branch  | tee /Users/timm/tmp/branch/X264_AllMeasurements.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/rs-6d-c3_obj1.csv -e branch  | tee /Users/timm/tmp/branch/rs-6d-c3_obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/rs-6d-c3_obj2.csv -e branch  | tee /Users/timm/tmp/branch/rs-6d-c3_obj2.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/sol-6d-c2-obj1.csv -e branch  | tee /Users/timm/tmp/branch/sol-6d-c2-obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/wc+rs-3d-c4-obj1.csv -e branch  | tee /Users/timm/tmp/branch/wc+rs-3d-c4-obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/wc+sol-3d-c4-obj1.csv -e branch  | tee /Users/timm/tmp/branch/wc+sol-3d-c4-obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/wc+wc-3d-c4-obj1.csv -e branch  | tee /Users/timm/tmp/branch/wc+wc-3d-c4-obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/config/wc-6d-c1-obj1.csv -e branch  | tee /Users/timm/tmp/branch/wc-6d-c1-obj1.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/hpo/healthCloseIsses12mths0001-hard.csv -e branch  | tee /Users/timm/tmp/branch/healthCloseIsses12mths0001-hard.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/hpo/healthCloseIsses12mths0011-easy.csv -e branch  | tee /Users/timm/tmp/branch/healthCloseIsses12mths0011-easy.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/misc/Wine_quality.csv -e branch  | tee /Users/timm/tmp/branch/Wine_quality.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/misc/auto93.csv -e branch  | tee /Users/timm/tmp/branch/auto93.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/coc1000.csv -e branch  | tee /Users/timm/tmp/branch/coc1000.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/nasa93dem.csv -e branch  | tee /Users/timm/tmp/branch/nasa93dem.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/pom3a.csv -e branch  | tee /Users/timm/tmp/branch/pom3a.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/pom3b.csv -e branch  | tee /Users/timm/tmp/branch/pom3b.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/pom3c.csv -e branch  | tee /Users/timm/tmp/branch/pom3c.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/pom3d.csv -e branch  | tee /Users/timm/tmp/branch/pom3d.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/xomo_flight.csv -e branch  | tee /Users/timm/tmp/branch/xomo_flight.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/xomo_ground.csv -e branch  | tee /Users/timm/tmp/branch/xomo_ground.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/xomo_osp.csv -e branch  | tee /Users/timm/tmp/branch/xomo_osp.csv & 
python3 /Users/timm/gits/timm/ezr/ezr.py  -D -t /Users/timm/gits/timm/ezr/data/optimize/process/xomo_osp2.csv -e branch  | tee /Users/timm/tmp/branch/xomo_osp2.csv & 
